version: 0.1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2019
configuration: Release
platform: Any CPU
environment:
  GH_TOKEN:
    secure: nzUU8F4CLe1EDxmKabW5Ym6NnL0SEK+VLft2D8oh72KEcfejyt1xWsQq9dMg6Wpt
  NUGET_API_KEY:
    secure: BmZ3/8sN8tg20TLTa0Qqw+L3JqM7G2K6wp/KLf+1gCkx29RvgHG+9CGAD80KGH7Q
before_build:
- pwsh: dotnet restore
build:
  parallel: true
  verbosity: minimal
artifacts:
- path: Jaml.Wpf\bin\Release\*.nupkg
  name: nupkg
- path: Jaml.Wpf\bin\Release\*.snupkg
  name: snupkg
deploy:
- provider: NuGet
  api_key: $(NUGET_API_KEY)
  artifact: /.*(\.|\.s)nupkg/
  on:
    branch: master
- provider: NuGet
  server: https://nuget.pkg.github.com/gigas002/index.json
  api_key: $(GH_TOKEN)
  username:
    secure: rZ2WjoUDzL3ZjbEuu/WA5g==
  artifact: /.*(\.)nupkg/
  on:
    branch: master